// Mock data for the BrainCast app

// Featured quizzes on the homepage
export const featuredQuizzes = [
  {
    id: "web3-basics",
    title: "Web3 Basics",
    description: "Test your knowledge of Web3 fundamentals",
    emoji: "🌐",
    plays: 1245,
    questions: [
      {
        text: "What is a blockchain?",
        type: "multiple-choice",
        options: [
          "A type of cryptocurrency",
          "A distributed ledger technology",
          "A programming language",
          "A web browser",
        ],
        correctAnswer: "A distributed ledger technology",
      },
      {
        text: "What does NFT stand for?",
        type: "multiple-choice",
        options: [
          "New Financial Transaction",
          "Non-Fungible Token",
          "Network File Transfer",
          "National Fintech Technology",
        ],
        correctAnswer: "Non-Fungible Token",
      },
      {
        text: "Which of these is NOT a cryptocurrency?",
        type: "multiple-choice",
        options: ["Bitcoin", "Ethereum", "Solana", "Fireblocks"],
        correctAnswer: "Fireblocks",
      },
    ],
    category: "web3",
    categoryName: "Web3",
    timeLimit: 60,
    topScore: 98,
  },
  {
    id: "country-flags",
    title: "Country Flags",
    description: "Can you identify these country flags?",
    emoji: "🏳️",
    plays: 2156,
    questions: [
      {
        text: "Which country does this flag belong to?",
        type: "image",
        imageUrl: "/placeholder.svg?height=200&width=300",
        correctAnswer: "Sweden",
      },
      {
        text: "Which country does this flag belong to?",
        type: "image",
        imageUrl: "/placeholder.svg?height=200&width=300",
        correctAnswer: "Brazil",
      },
      {
        text: "Which country does this flag belong to?",
        type: "image",
        imageUrl: "/placeholder.svg?height=200&width=300",
        correctAnswer: "Japan",
      },
    ],
    category: "geography",
    categoryName: "Geography",
    timeLimit: 30,
    topScore: 100,
  },
  {
    id: "european-capitals",
    title: "European Capitals",
    description: "Name the capital cities of European countries",
    emoji: "🏛️",
    plays: 1876,
    questions: [
      {
        text: "Name the capital cities of these European countries",
        type: "list",
        correctAnswers: [
          "paris",
          "london",
          "berlin",
          "rome",
          "madrid",
          "lisbon",
          "amsterdam",
          "brussels",
          "vienna",
          "athens",
        ],
      },
    ],
    category: "geography",
    categoryName: "Geography",
    timeLimit: 120,
    topScore: 90,
  },
  {
    id: "us-states",
    title: "US States on Map",
    description: "Can you locate these US states on a map?",
    emoji: "🗺️",
    plays: 1543,
    questions: [
      {
        text: "Click on the map to locate Texas",
        type: "map",
        mapUrl: "/placeholder.svg?height=256&width=400",
        correctCoordinates: { x: 38, y: 65 },
      },
      {
        text: "Click on the map to locate New York",
        type: "map",
        mapUrl: "/placeholder.svg?height=256&width=400",
        correctCoordinates: { x: 82, y: 32 },
      },
      {
        text: "Click on the map to locate California",
        type: "map",
        mapUrl: "/placeholder.svg?height=256&width=400",
        correctCoordinates: { x: 12, y: 42 },
      },
    ],
    category: "geography",
    categoryName: "Geography",
    timeLimit: 45,
    topScore: 85,
  },
]

// Trending quizzes
export const trendingQuizzes = [
  {
    id: "company-logos",
    title: "Tech Company Logos",
    description: "Can you identify these tech company logos?",
    emoji: "🏢",
    plays: 3421,
    questions: [
      {
        text: "Which company does this logo belong to?",
        type: "image",
        imageUrl: "/placeholder.svg?height=200&width=300",
        correctAnswer: "Apple",
      },
      {
        text: "Which company does this logo belong to?",
        type: "image",
        imageUrl: "/placeholder.svg?height=200&width=300",
        correctAnswer: "Google",
      },
      {
        text: "Which company does this logo belong to?",
        type: "image",
        imageUrl: "/placeholder.svg?height=200&width=300",
        correctAnswer: "Microsoft",
      },
    ],
    category: "business",
    categoryName: "Business",
    timeLimit: 30,
    topScore: 95,
  },
  {
    id: "crypto-projects",
    title: "Crypto Project Logos",
    description: "Test your knowledge of crypto project logos",
    emoji: "💰",
    plays: 2187,
    questions: [
      {
        text: "Which crypto project does this logo belong to?",
        type: "image",
        imageUrl: "/placeholder.svg?height=200&width=300",
        correctAnswer: "Ethereum",
      },
      {
        text: "Which crypto project does this logo belong to?",
        type: "image",
        imageUrl: "/placeholder.svg?height=200&width=300",
        correctAnswer: "Solana",
      },
      {
        text: "Which crypto project does this logo belong to?",
        type: "image",
        imageUrl: "/placeholder.svg?height=200&width=300",
        correctAnswer: "Polygon",
      },
    ],
    category: "web3",
    categoryName: "Web3",
    timeLimit: 30,
    topScore: 90,
  },
  {
    id: "world-cities",
    title: "World Cities on Map",
    description: "Can you locate these major world cities?",
    emoji: "🌆",
    plays: 1876,
    questions: [
      {
        text: "Click on the map to locate Tokyo",
        type: "map",
        mapUrl: "/placeholder.svg?height=256&width=400",
        correctCoordinates: { x: 82, y: 42 },
      },
      {
        text: "Click on the map to locate London",
        type: "map",
        mapUrl: "/placeholder.svg?height=256&width=400",
        correctCoordinates: { x: 48, y: 32 },
      },
      {
        text: "Click on the map to locate Rio de Janeiro",
        type: "map",
        mapUrl: "/placeholder.svg?height=256&width=400",
        correctCoordinates: { x: 35, y: 68 },
      },
    ],
    category: "geography",
    categoryName: "Geography",
    timeLimit: 45,
    topScore: 80,
  },
  {
    id: "movie-quotes",
    title: "Famous Movie Quotes",
    description: "Can you name the movies from these famous quotes?",
    emoji: "🎬",
    plays: 2543,
    questions: [
      {
        text: '"May the Force be with you."',
        type: "multiple-choice",
        options: ["Star Wars", "The Matrix", "The Lord of the Rings", "Harry Potter"],
        correctAnswer: "Star Wars",
      },
      {
        text: '"I\'ll be back."',
        type: "multiple-choice",
        options: ["The Terminator", "Die Hard", "Rambo", "Rocky"],
        correctAnswer: "The Terminator",
      },
      {
        text: '"Life is like a box of chocolates."',
        type: "multiple-choice",
        options: ["The Godfather", "Forrest Gump", "Titanic", "Pulp Fiction"],
        correctAnswer: "Forrest Gump",
      },
    ],
    category: "entertainment",
    categoryName: "Entertainment",
    timeLimit: 30,
    topScore: 100,
  },
  {
    id: "nba-teams",
    title: "NBA Teams",
    description: "Name all 30 NBA teams",
    emoji: "🏀",
    plays: 1987,
    questions: [
      {
        text: "Name all 30 NBA teams",
        type: "list",
        correctAnswers: [
          "lakers",
          "celtics",
          "warriors",
          "bulls",
          "heat",
          "knicks",
          "nets",
          "76ers",
          "raptors",
          "bucks",
          "cavaliers",
          "pacers",
          "pistons",
          "hawks",
          "hornets",
          "magic",
          "wizards",
          "nuggets",
          "timberwolves",
          "thunder",
          "trail blazers",
          "jazz",
          "suns",
          "kings",
          "clippers",
          "mavericks",
          "rockets",
          "grizzlies",
          "pelicans",
          "spurs",
        ],
      },
    ],
    category: "sports",
    categoryName: "Sports",
    timeLimit: 180,
    topScore: 87,
  },
]

// All quizzes
export const quizzes = [
  ...featuredQuizzes,
  ...trendingQuizzes,
  {
    id: "farcaster-trivia",
    title: "Farcaster Trivia",
    description: "How well do you know Farcaster?",
    emoji: "🟣",
    plays: 876,
    questions: [
      {
        text: "When was Farcaster founded?",
        type: "multiple-choice",
        options: ["2018", "2019", "2020", "2021"],
        correctAnswer: "2020",
      },
      {
        text: "What is a 'cast' in Farcaster?",
        type: "multiple-choice",
        options: ["A private message", "A public post", "A channel", "A user profile"],
        correctAnswer: "A public post",
      },
      {
        text: "What is the name of Farcaster's mobile app?",
        type: "multiple-choice",
        options: ["Farcaster", "Warpcast", "Castaway", "Faraway"],
        correctAnswer: "Warpcast",
      },
    ],
    category: "web3",
    categoryName: "Web3",
    timeLimit: 45,
    topScore: 100,
  },
]

// Categories
export const categories = [
  {
    id: "web3",
    name: "Web3",
    emoji: "🌐",
    quizCount: 12,
  },
  {
    id: "geography",
    name: "Geography",
    emoji: "🌍",
    quizCount: 15,
  },
  {
    id: "entertainment",
    name: "Entertainment",
    emoji: "🎬",
    quizCount: 20,
  },
  {
    id: "sports",
    name: "Sports",
    emoji: "⚽",
    quizCount: 14,
  },
  {
    id: "science",
    name: "Science",
    emoji: "🔬",
    quizCount: 8,
  },
  {
    id: "history",
    name: "History",
    emoji: "📜",
    quizCount: 10,
  },
]

// User quizzes
export const userQuizzes = {
  taken: [
    {
      id: "web3-basics",
      title: "Web3 Basics",
      description: "Test your knowledge of Web3 fundamentals",
      score: 80,
      date: "2 days ago",
      plays: 1245,
    },
    {
      id: "country-flags",
      title: "Country Flags",
      description: "Can you identify these country flags?",
      score: 100,
      date: "1 week ago",
      plays: 2156,
    },
    {
      id: "us-states",
      title: "US States on Map",
      description: "Can you locate these US states on a map?",
      score: 60,
      date: "2 weeks ago",
      plays: 1543,
    },
  ],
  created: [
    {
      id: "crypto-trends-2024",
      title: "Crypto Trends 2024",
      description: "Test your knowledge of the latest crypto trends",
      status: "Published",
      date: "3 days ago",
      plays: 87,
    },
    {
      id: "web3-advanced",
      title: "Web3 Advanced Concepts",
      description: "Deep dive into advanced Web3 concepts",
      status: "Draft",
      date: "1 week ago",
      plays: 0,
    },
  ],
}

// User achievements
export const userAchievements = [
  {
    id: 1,
    name: "Quiz Novice",
    description: "Complete 5 quizzes",
    emoji: "🎯",
    unlocked: true,
  },
  {
    id: 2,
    name: "Perfect Score",
    description: "Get 100% on any quiz",
    emoji: "💯",
    unlocked: true,
  },
  {
    id: 3,
    name: "Web3 Wizard",
    description: "Complete all Web3 category quizzes",
    emoji: "🧙‍♂️",
    unlocked: false,
    progress: 60,
    progressText: "3/5 completed",
  },
  {
    id: 4,
    name: "Quiz Creator",
    description: "Create your first quiz",
    emoji: "✏️",
    unlocked: true,
  },
  {
    id: 5,
    name: "Challenge Champion",
    description: "Win 10 challenges against friends",
    emoji: "🏆",
    unlocked: false,
    progress: 30,
    progressText: "3/10 won",
  },
  {
    id: 6,
    name: "Geography Expert",
    description: "Score 90%+ on 5 geography quizzes",
    emoji: "🌎",
    unlocked: false,
    progress: 40,
    progressText: "2/5 completed",
  },
]

// User challenges
export const userChallenges = {
  active: [
    {
      id: "c1",
      challenger: {
        username: "brainiac",
        displayName: "Brainiac",
        pfpUrl: "/placeholder.svg?height=40&width=40",
      },
      quizId: "web3-basics",
      quizTitle: "Web3 Basics",
      challengerScore: 90,
      questions: 10,
      timeLeft: "23 hours left",
    },
    {
      id: "c2",
      challenger: {
        username: "triviawhiz",
        displayName: "Trivia Whiz",
        pfpUrl: "/placeholder.svg?height=40&width=40",
      },
      quizId: "country-flags",
      quizTitle: "Country Flags",
      challengerScore: 80,
      questions: 5,
      timeLeft: "2 days left",
    },
  ],
  sent: [
    {
      id: "c3",
      recipient: {
        username: "factfinder",
        displayName: "Fact Finder",
        pfpUrl: "/placeholder.svg?height=40&width=40",
      },
      quizTitle: "US States on Map",
      yourScore: 85,
      sentDate: "1 day ago",
      status: "Pending",
    },
    {
      id: "c4",
      recipient: {
        username: "knowledgeseeker",
        displayName: "Knowledge Seeker",
        pfpUrl: "/placeholder.svg?height=40&width=40",
      },
      quizTitle: "Movie Quotes",
      yourScore: 70,
      sentDate: "3 days ago",
      status: "Accepted",
    },
  ],
  history: [
    {
      id: "c5",
      opponent: {
        username: "brainiac",
        displayName: "Brainiac",
        pfpUrl: "/placeholder.svg?height=40&width=40",
      },
      quizTitle: "Crypto Project Logos",
      yourScore: 90,
      opponentScore: 85,
      date: "1 week ago",
      result: "Won",
    },
    {
      id: "c6",
      opponent: {
        username: "triviawhiz",
        displayName: "Trivia Whiz",
        pfpUrl: "/placeholder.svg?height=40&width=40",
      },
      quizTitle: "European Capitals",
      yourScore: 75,
      opponentScore: 85,
      date: "2 weeks ago",
      result: "Lost",
    },
    {
      id: "c7",
      opponent: {
        username: "factfinder",
        displayName: "Fact Finder",
        pfpUrl: "/placeholder.svg?height=40&width=40",
      },
      quizTitle: "Web3 Basics",
      yourScore: 80,
      opponentScore: 80,
      date: "3 weeks ago",
      result: "Tied",
    },
  ],
}

export const leaderboardUsers = [
  {
    fid: 1001,
    username: "quizmaster",
    displayName: "Quiz Master",
    pfpUrl: "/placeholder.svg?height=40&width=40",
    score: 12450,
    quizzesTaken: 142,
  },
  {
    fid: 1002,
    username: "brainiac",
    displayName: "Brainiac",
    pfpUrl: "/placeholder.svg?height=40&width=40",
    score: 10820,
    quizzesTaken: 98,
  },
  {
    fid: 1003,
    username: "triviawhiz",
    displayName: "Trivia Whiz",
    pfpUrl: "/placeholder.svg?height=40&width=40",
    score: 9540,
    quizzesTaken: 87,
  },
  {
    fid: 1004,
    username: "knowledgeseeker",
    displayName: "Knowledge Seeker",
    pfpUrl: "/placeholder.svg?height=40&width=40",
    score: 8970,
    quizzesTaken: 76,
  },
  {
    fid: 1005,
    username: "factfinder",
    displayName: "Fact Finder",
    pfpUrl: "/placeholder.svg?height=40&width=40",
    score: 7650,
    quizzesTaken: 65,
  },
]
